@hostname = localhost
@port = 8888
@host = {{hostname}}:{{port}}
@createAt ={{$datetime iso8601}}

###　创建用户

POST /users HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-Cache

{
    "username": "fx",
    "password": "123456"
}


###　更新用户

PUT  /users/id/1 HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-Cache

{
    "username": "foxware",
    "password": "123456"
}


###　删除用户
DELETE   /users/id/1 HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-Cache

### 获取所有的注册用户

GET   /users HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-Cache

###　获取指定用户信息
GET   /users/id/2 HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-Cache

###　用户登陆验证

POST /login HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-Cache

{
    "username": "fx",
    "password": "123456"
}

