// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"blog/users/rpc/internal/logic"
	"blog/users/rpc/internal/svc"
	"blog/users/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.ReqUser) (*user.RespLogin, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Create(ctx context.Context, in *user.ReqUser) (*user.CommResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *UserServer) Update(ctx context.Context, in *user.User) (*user.CommResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *UserServer) Delete(ctx context.Context, in *user.ReqUserId) (*user.CommResp, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *UserServer) Get(ctx context.Context, in *user.ReqUserId) (*user.User, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *UserServer) GetAll(ctx context.Context, in *user.ReqGetAll) (*user.RespGetAll, error) {
	l := logic.NewGetAllLogic(ctx, s.svcCtx)
	return l.GetAll(in)
}
