// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"blog/users/rpc/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	ReqUserId  = user.ReqUserId
	ReqGetAll  = user.ReqGetAll
	RespGetAll = user.RespGetAll
	ReqUser    = user.ReqUser
	User       = user.User
	CommResp   = user.CommResp
	LoginReq   = user.LoginReq
	RespLogin  = user.RespLogin

	User interface {
		Login(ctx context.Context, in *ReqUser) (*RespLogin, error)
		Create(ctx context.Context, in *ReqUser) (*CommResp, error)
		Update(ctx context.Context, in *User) (*CommResp, error)
		Delete(ctx context.Context, in *ReqUserId) (*CommResp, error)
		Get(ctx context.Context, in *ReqUserId) (*User, error)
		GetAll(ctx context.Context, in *ReqGetAll) (*RespGetAll, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *ReqUser) (*RespLogin, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUser) Create(ctx context.Context, in *ReqUser) (*CommResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Create(ctx, in)
}

func (m *defaultUser) Update(ctx context.Context, in *User) (*CommResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Update(ctx, in)
}

func (m *defaultUser) Delete(ctx context.Context, in *ReqUserId) (*CommResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Delete(ctx, in)
}

func (m *defaultUser) Get(ctx context.Context, in *ReqUserId) (*User, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Get(ctx, in)
}

func (m *defaultUser) GetAll(ctx context.Context, in *ReqGetAll) (*RespGetAll, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetAll(ctx, in)
}
